package standalone.com.sun.tools.javac.resources;

public final class ct extends java.util.ListResourceBundle {
    protected final Object[][] getContents() {
        return new Object[][] {
            { "apple.laf.*", "hidden" },
            { "apple.security.*", "hidden" },
            { "com.apple.eawt.*", "hidden" },
            { "com.apple.eawt.event.*", "hidden" },
            { "com.apple.eio.*", "hidden" },
            { "com.apple.laf.*", "hidden" },
            { "com.oracle.webservices.internal.api.*", "hidden" },
            { "com.oracle.webservices.internal.api.databinding.*", "hidden" },
            { "com.oracle.webservices.internal.api.message.*", "hidden" },
            { "com.oracle.webservices.internal.impl.encoding.*", "hidden" },
            { "com.oracle.webservices.internal.impl.internalspi.encoding.*", "hidden" },
            { "com.oracle.xmlns.internal.webservices.jaxws_databinding.*", "hidden" },
            { "standalone.com.sun.accessibility.internal.resources.*", "proprietary" },
            { "standalone.com.sun.activation.registries.*", "hidden" },
            { "standalone.com.sun.awt.*", "proprietary" },
            { "standalone.com.sun.beans.*", "proprietary" },
            { "standalone.com.sun.beans.decoder.*", "hidden" },
            { "standalone.com.sun.beans.editors.*", "hidden" },
            { "standalone.com.sun.beans.finder.*", "hidden" },
            { "standalone.com.sun.beans.infos.*", "hidden" },
            { "standalone.com.sun.beans.introspect.*", "hidden" },
            { "standalone.com.sun.beans.util.*", "hidden" },
            { "standalone.com.sun.corba.se.impl.activation.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.copyobject.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.corba.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.dynamicany.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.encoding.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.interceptors.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.io.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.ior.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.ior.iiop.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.javax.rmi.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.javax.rmi.CORBA.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.legacy.connection.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.logging.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.monitoring.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.naming.cosnaming.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.naming.namingutil.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.naming.pcosnaming.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.oa.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.oa.poa.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.oa.toa.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.orb.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.orbutil.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.orbutil.closure.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.orbutil.concurrent.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.orbutil.fsm.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.orbutil.graph.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.orbutil.threadpool.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.presentation.rmi.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.protocol.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.protocol.giopmsgheaders.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.resolver.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.transport.*", "proprietary" },
            { "standalone.com.sun.corba.se.impl.util.*", "proprietary" },
            { "standalone.com.sun.corba.se.internal.CosNaming.*", "proprietary" },
            { "standalone.com.sun.corba.se.internal.Interceptors.*", "proprietary" },
            { "standalone.com.sun.corba.se.internal.POA.*", "proprietary" },
            { "standalone.com.sun.corba.se.internal.corba.*", "proprietary" },
            { "standalone.com.sun.corba.se.internal.iiop.*", "proprietary" },
            { "standalone.com.sun.corba.se.org.omg.CORBA.*", "proprietary" },
            { "standalone.com.sun.corba.se.pept.broker.*", "proprietary" },
            { "standalone.com.sun.corba.se.pept.encoding.*", "proprietary" },
            { "standalone.com.sun.corba.se.pept.protocol.*", "proprietary" },
            { "standalone.com.sun.corba.se.pept.transport.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.activation.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.activation.InitialNameServicePackage.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.activation.LocatorPackage.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.activation.RepositoryPackage.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.copyobject.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.encoding.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.extension.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.ior.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.ior.iiop.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.legacy.connection.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.legacy.interceptor.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.logging.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.monitoring.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.oa.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.orb.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.orbutil.closure.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.orbutil.fsm.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.orbutil.proxy.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.orbutil.threadpool.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.presentation.rmi.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.protocol.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.resolver.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.servicecontext.*", "proprietary" },
            { "standalone.com.sun.corba.se.spi.transport.*", "proprietary" },
            { "standalone.com.sun.demo.jvmti.hprof.*", "hidden" },
            { "standalone.com.sun.imageio.plugins.bmp.*", "proprietary" },
            { "standalone.com.sun.imageio.plugins.common.*", "proprietary" },
            { "standalone.com.sun.imageio.plugins.gif.*", "proprietary" },
            { "standalone.com.sun.imageio.plugins.jpeg.*", "proprietary" },
            { "standalone.com.sun.imageio.plugins.png.*", "proprietary" },
            { "standalone.com.sun.imageio.plugins.wbmp.*", "proprietary" },
            { "standalone.com.sun.imageio.spi.*", "proprietary" },
            { "standalone.com.sun.imageio.stream.*", "hidden" },
            { "standalone.com.sun.istack.internal.*", "hidden" },
            { "standalone.com.sun.istack.internal.localization.*", "hidden" },
            { "standalone.com.sun.istack.internal.logging.*", "hidden" },
            { "standalone.com.sun.java.swing.*", "proprietary" },
            { "standalone.com.sun.java.swing.plaf.gtk.resources.*", "proprietary" },
            { "standalone.com.sun.java.swing.plaf.motif.resources.*", "proprietary" },
            { "standalone.com.sun.java.swing.plaf.nimbus.*", "proprietary" },
            { "standalone.com.sun.java.swing.plaf.windows.resources.*", "proprietary" },
            { "standalone.com.sun.java.util.jar.pack.*", "proprietary compact1" },
            { "standalone.com.sun.java_cup.internal.runtime.*", "proprietary compact2" },
            { "standalone.com.sun.jmx.defaults.*", "proprietary compact3" },
            { "standalone.com.sun.jmx.interceptor.*", "proprietary compact3" },
            { "standalone.com.sun.jmx.mbeanserver.*", "proprietary compact3" },
            { "standalone.com.sun.jmx.remote.internal.*", "proprietary compact3" },
            { "standalone.com.sun.jmx.remote.protocol.rmi.*", "proprietary compact3" },
            { "standalone.com.sun.jmx.remote.security.*", "proprietary compact3" },
            { "standalone.com.sun.jmx.remote.util.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.cosnaming.*", "proprietary" },
            { "standalone.com.sun.jndi.dns.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.ldap.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.ldap.ext.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.ldap.pool.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.ldap.sasl.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.rmi.registry.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.toolkit.corba.*", "proprietary" },
            { "standalone.com.sun.jndi.toolkit.ctx.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.toolkit.dir.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.toolkit.url.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.url.corbaname.*", "proprietary" },
            { "standalone.com.sun.jndi.url.dns.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.url.iiop.*", "proprietary" },
            { "standalone.com.sun.jndi.url.iiopname.*", "proprietary" },
            { "standalone.com.sun.jndi.url.ldap.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.url.ldaps.*", "proprietary compact3" },
            { "standalone.com.sun.jndi.url.rmi.*", "proprietary compact3" },
            { "standalone.com.sun.management.*", "compact3" },
            { "standalone.com.sun.media.sound.*", "proprietary" },
            { "standalone.com.sun.naming.internal.*", "proprietary compact3" },
            { "standalone.com.sun.net.httpserver.*", "compact2" },
            { "standalone.com.sun.net.httpserver.spi.*", "compact2" },
            { "standalone.com.sun.net.ssl.*", "compact1" },
            { "standalone.com.sun.net.ssl.internal.www.protocol.https.*", "proprietary compact1" },
            { "standalone.com.sun.nio.file.*", "proprietary compact1" },
            { "standalone.com.sun.nio.sctp.*", "compact3" },
            { "standalone.com.sun.org.apache.bcel.internal.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.bcel.internal.classfile.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.bcel.internal.generic.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.bcel.internal.util.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.regexp.internal.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.extensions.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.lib.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.res.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.templates.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.utils.*", "hidden" },
            { "standalone.com.sun.org.apache.xalan.internal.xslt.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.xsltc.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.xsltc.cmdline.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.xsltc.cmdline.getopt.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.xsltc.compiler.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.xsltc.compiler.util.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.xsltc.dom.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.xsltc.runtime.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.xsltc.runtime.output.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.xsltc.trax.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xalan.internal.xsltc.util.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.dom.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.dom.events.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.dtd.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.dtd.models.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.dv.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.dv.dtd.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.dv.util.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.dv.xs.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.io.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.msg.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.validation.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.xpath.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.xpath.regex.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.xs.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.xs.identity.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.xs.models.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.xs.opti.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.xs.traversers.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.impl.xs.util.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.jaxp.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.jaxp.datatype.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.jaxp.validation.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.parsers.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.util.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.utils.*", "hidden" },
            { "standalone.com.sun.org.apache.xerces.internal.xinclude.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.xni.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.xni.grammars.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.xni.parser.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.xpointer.*", "hidden" },
            { "standalone.com.sun.org.apache.xerces.internal.xs.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xerces.internal.xs.datatypes.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.dtm.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xml.internal.dtm.ref.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xml.internal.dtm.ref.dom2dtm.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xml.internal.dtm.ref.sax2dtm.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xml.internal.res.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xml.internal.resolver.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.resolver.helpers.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.resolver.readers.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.resolver.tools.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.algorithms.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.algorithms.implementations.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.c14n.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.c14n.helper.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.c14n.implementations.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.encryption.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.exceptions.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.keys.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.keys.content.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.keys.content.keyvalues.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.keys.content.x509.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.keys.keyresolver.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.keys.keyresolver.implementations.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.keys.storage.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.keys.storage.implementations.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.signature.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.signature.reference.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.transforms.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.transforms.implementations.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.transforms.params.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.utils.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.utils.resolver.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.security.utils.resolver.implementations.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.serialize.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xml.internal.serializer.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xml.internal.serializer.dom3.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.serializer.utils.*", "hidden" },
            { "standalone.com.sun.org.apache.xml.internal.utils.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xml.internal.utils.res.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xpath.internal.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xpath.internal.axes.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xpath.internal.compiler.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xpath.internal.domapi.*", "hidden" },
            { "standalone.com.sun.org.apache.xpath.internal.functions.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xpath.internal.jaxp.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xpath.internal.objects.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xpath.internal.operations.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xpath.internal.patterns.*", "proprietary compact2" },
            { "standalone.com.sun.org.apache.xpath.internal.res.*", "proprietary compact2" },
            { "standalone.com.sun.org.glassfish.external.amx.*", "hidden" },
            { "standalone.com.sun.org.glassfish.external.arc.*", "hidden" },
            { "standalone.com.sun.org.glassfish.external.probe.provider.*", "hidden" },
            { "standalone.com.sun.org.glassfish.external.probe.provider.annotations.*", "hidden" },
            { "standalone.com.sun.org.glassfish.external.statistics.*", "hidden" },
            { "standalone.com.sun.org.glassfish.external.statistics.annotations.*", "hidden" },
            { "standalone.com.sun.org.glassfish.external.statistics.impl.*", "hidden" },
            { "standalone.com.sun.org.glassfish.gmbal.*", "hidden" },
            { "standalone.com.sun.org.glassfish.gmbal.util.*", "hidden" },
            { "standalone.com.sun.org.omg.CORBA.*", "proprietary" },
            { "standalone.com.sun.org.omg.CORBA.ValueDefPackage.*", "proprietary" },
            { "standalone.com.sun.org.omg.CORBA.portable.*", "proprietary" },
            { "standalone.com.sun.org.omg.SendingContext.*", "proprietary" },
            { "standalone.com.sun.org.omg.SendingContext.CodeBasePackage.*", "proprietary" },
            { "standalone.com.sun.rmi.rmid.*", "proprietary compact2" },
            { "standalone.com.sun.rowset.*", "proprietary compact3" },
            { "standalone.com.sun.rowset.internal.*", "proprietary compact3" },
            { "standalone.com.sun.rowset.providers.*", "proprietary compact3" },
            { "standalone.com.sun.security.auth.*", "compact3" },
            { "standalone.com.sun.security.auth.callback.*", "compact3" },
            { "standalone.com.sun.security.auth.login.*", "compact3" },
            { "standalone.com.sun.security.auth.module.*", "compact3" },
            { "standalone.com.sun.security.cert.internal.x509.*", "proprietary compact1" },
            { "standalone.com.sun.security.jgss.*", "compact3" },
            { "standalone.com.sun.security.ntlm.*", "hidden" },
            { "standalone.com.sun.security.sasl.*", "proprietary compact3" },
            { "standalone.com.sun.security.sasl.digest.*", "proprietary compact3" },
            { "standalone.com.sun.security.sasl.gsskerb.*", "proprietary compact3" },
            { "standalone.com.sun.security.sasl.ntlm.*", "hidden" },
            { "standalone.com.sun.security.sasl.util.*", "proprietary compact3" },
            { "standalone.com.sun.swing.internal.plaf.basic.resources.*", "proprietary" },
            { "standalone.com.sun.swing.internal.plaf.metal.resources.*", "proprietary" },
            { "standalone.com.sun.swing.internal.plaf.synth.resources.*", "proprietary" },
            { "standalone.com.sun.tracing.*", "proprietary compact3" },
            { "standalone.com.sun.tracing.dtrace.*", "proprietary compact3" },
            { "standalone.com.sun.xml.internal.bind.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.annotation.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.api.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.api.impl.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.marshaller.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.unmarshaller.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.util.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.bytecode.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.model.annotation.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.model.core.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.model.impl.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.model.nav.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.model.runtime.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.model.util.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.runtime.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.runtime.output.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.runtime.property.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.runtime.reflect.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.runtime.reflect.opt.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.runtime.unmarshaller.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.schemagen.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.schemagen.episode.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.schemagen.xmlschema.*", "hidden" },
            { "standalone.com.sun.xml.internal.bind.v2.util.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.algorithm.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.alphabet.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.dom.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.org.apache.xerces.util.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.sax.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.stax.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.stax.events.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.stax.factory.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.stax.util.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.tools.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.util.*", "hidden" },
            { "standalone.com.sun.xml.internal.fastinfoset.vocab.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.client.p2p.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.packaging.mime.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.packaging.mime.internet.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.packaging.mime.util.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.soap.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.soap.dynamic.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.soap.impl.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.soap.name.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.soap.ver1_1.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.soap.ver1_2.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.util.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.util.stax.*", "hidden" },
            { "standalone.com.sun.xml.internal.messaging.saaj.util.transform.*", "hidden" },
            { "standalone.com.sun.xml.internal.org.jvnet.fastinfoset.*", "hidden" },
            { "standalone.com.sun.xml.internal.org.jvnet.fastinfoset.sax.*", "hidden" },
            { "standalone.com.sun.xml.internal.org.jvnet.fastinfoset.sax.helpers.*", "hidden" },
            { "standalone.com.sun.xml.internal.org.jvnet.fastinfoset.stax.*", "hidden" },
            { "standalone.com.sun.xml.internal.org.jvnet.mimepull.*", "hidden" },
            { "standalone.com.sun.xml.internal.org.jvnet.staxex.*", "hidden" },
            { "standalone.com.sun.xml.internal.org.jvnet.staxex.util.*", "hidden" },
            { "standalone.com.sun.xml.internal.stream.*", "hidden" },
            { "standalone.com.sun.xml.internal.stream.buffer.*", "hidden" },
            { "standalone.com.sun.xml.internal.stream.buffer.sax.*", "hidden" },
            { "standalone.com.sun.xml.internal.stream.buffer.stax.*", "hidden" },
            { "standalone.com.sun.xml.internal.stream.dtd.*", "hidden" },
            { "standalone.com.sun.xml.internal.stream.dtd.nonvalidating.*", "hidden" },
            { "standalone.com.sun.xml.internal.stream.events.*", "hidden" },
            { "standalone.com.sun.xml.internal.stream.util.*", "hidden" },
            { "standalone.com.sun.xml.internal.stream.writers.*", "hidden" },
            { "standalone.com.sun.xml.internal.txw2.*", "hidden" },
            { "standalone.com.sun.xml.internal.txw2.annotation.*", "hidden" },
            { "standalone.com.sun.xml.internal.txw2.output.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.addressing.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.addressing.model.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.addressing.policy.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.addressing.v200408.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.addressing.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.client.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.config.management.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.config.management.policy.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.databinding.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.fastinfoset.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.ha.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.handler.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.message.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.message.saaj.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.message.stream.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.model.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.model.soap.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.model.wsdl.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.model.wsdl.editable.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.pipe.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.pipe.helper.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.policy.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.policy.subject.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.server.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.streaming.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.wsdl.parser.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.api.wsdl.writer.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.assembler.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.assembler.dev.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.assembler.jaxws.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.binding.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.client.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.client.dispatch.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.client.sei.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.commons.xmlutil.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.config.management.policy.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.config.metro.dev.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.config.metro.util.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.db.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.db.glassfish.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.developer.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.dump.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.encoding.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.encoding.fastinfoset.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.encoding.policy.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.encoding.soap.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.encoding.soap.streaming.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.encoding.xml.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.fault.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.handler.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.message.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.message.jaxb.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.message.saaj.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.message.source.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.message.stream.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.model.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.model.soap.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.model.wsdl.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.org.objectweb.asm.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.policy.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.policy.jaxws.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.policy.jaxws.spi.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.policy.privateutil.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.policy.sourcemodel.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.policy.sourcemodel.attach.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.policy.sourcemodel.wspolicy.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.policy.spi.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.policy.subject.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.protocol.soap.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.protocol.xml.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.resources.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.runtime.config.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.server.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.server.provider.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.server.sei.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.spi.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.spi.db.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.streaming.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.transport.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.transport.http.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.transport.http.client.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.transport.http.server.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.util.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.util.exception.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.util.pipe.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.util.xml.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.wsdl.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.wsdl.parser.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.wsdl.writer.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.wsdl.writer.document.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.wsdl.writer.document.http.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.wsdl.writer.document.soap.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.wsdl.writer.document.soap12.*", "hidden" },
            { "standalone.com.sun.xml.internal.ws.wsdl.writer.document.xsd.*", "hidden" },
            { "java.awt.dnd.peer.*", "proprietary" },
            { "java.awt.peer.*", "proprietary" },
            { "java.desktop.macosx.classes.com.apple.laf.resources.*", "hidden" },
            { "java.desktop.macosx.classes.sun.awt.resources.*", "hidden" },
            { "java.desktop.windows.classes.sun.awt.windows.*", "hidden" },
            { "java.io.*", "compact1" },
            { "java.lang.*", "compact1" },
            { "java.lang.annotation.*", "compact1" },
            { "java.lang.instrument.*", "compact3" },
            { "java.lang.invoke.*", "compact1" },
            { "java.lang.management.*", "compact3" },
            { "java.lang.ref.*", "compact1" },
            { "java.lang.reflect.*", "compact1" },
            { "java.math.*", "compact1" },
            { "java.net.*", "compact1" },
            { "java.nio.*", "compact1" },
            { "java.nio.channels.*", "compact1" },
            { "java.nio.channels.spi.*", "compact1" },
            { "java.nio.charset.*", "compact1" },
            { "java.nio.charset.spi.*", "compact1" },
            { "java.nio.file.*", "compact1" },
            { "java.nio.file.attribute.*", "compact1" },
            { "java.nio.file.spi.*", "compact1" },
            { "java.rmi.*", "compact2" },
            { "java.rmi.activation.*", "compact2" },
            { "java.rmi.dgc.*", "compact2" },
            { "java.rmi.registry.*", "compact2" },
            { "java.rmi.server.*", "compact2" },
            { "java.security.*", "compact1" },
            { "java.security.cert.*", "compact1" },
            { "java.security.interfaces.*", "compact1" },
            { "java.security.spec.*", "compact1" },
            { "java.sql.*", "compact2" },
            { "java.text.*", "compact1" },
            { "java.text.spi.*", "compact1" },
            { "java.time.*", "compact1" },
            { "java.time.chrono.*", "compact1" },
            { "java.time.format.*", "compact1" },
            { "java.time.temporal.*", "compact1" },
            { "java.time.zone.*", "compact1" },
            { "java.util.*", "compact1" },
            { "java.util.concurrent.*", "compact1" },
            { "java.util.concurrent.atomic.*", "compact1" },
            { "java.util.concurrent.locks.*", "compact1" },
            { "java.util.function.*", "compact1" },
            { "java.util.jar.*", "compact1" },
            { "java.util.logging.*", "compact1" },
            { "java.util.prefs.*", "compact3" },
            { "java.util.regex.*", "compact1" },
            { "java.util.spi.*", "compact1" },
            { "java.util.stream.*", "compact1" },
            { "java.util.zip.*", "compact1" },
            { "javax.annotation.processing.*", "compact3" },
            { "javax.lang.model.*", "compact3" },
            { "javax.lang.model.element.*", "compact3" },
            { "javax.lang.model.type.*", "compact3" },
            { "javax.lang.model.util.*", "compact3" },
            { "javax.management.*", "compact3" },
            { "javax.management.loading.*", "compact3" },
            { "javax.management.modelmbean.*", "compact3" },
            { "javax.management.monitor.*", "compact3" },
            { "javax.management.openmbean.*", "compact3" },
            { "javax.management.relation.*", "compact3" },
            { "javax.management.remote.*", "compact3" },
            { "javax.management.remote.rmi.*", "compact3" },
            { "javax.management.timer.*", "compact3" },
            { "javax.naming.*", "compact3" },
            { "javax.naming.directory.*", "compact3" },
            { "javax.naming.event.*", "compact3" },
            { "javax.naming.ldap.*", "compact3" },
            { "javax.naming.spi.*", "compact3" },
            { "javax.net.*", "compact1" },
            { "javax.net.ssl.*", "compact1" },
            { "javax.rmi.ssl.*", "compact2" },
            { "javax.script.*", "compact1" },
            { "javax.security.auth.*", "compact1" },
            { "javax.security.auth.callback.*", "compact1" },
            { "javax.security.auth.kerberos.*", "compact3" },
            { "javax.security.auth.login.*", "compact1" },
            { "javax.security.auth.spi.*", "compact1" },
            { "javax.security.auth.x500.*", "compact1" },
            { "javax.security.cert.*", "compact1" },
            { "javax.security.sasl.*", "compact3" },
            { "javax.smartcardio.*", "compact3" },
            { "javax.sql.*", "compact2" },
            { "javax.sql.rowset.*", "compact3" },
            { "javax.sql.rowset.serial.*", "compact3" },
            { "javax.sql.rowset.spi.*", "compact3" },
            { "javax.tools.*", "compact3" },
            { "javax.transaction.xa.*", "compact2" },
            { "javax.xml.*", "compact2" },
            { "javax.xml.crypto.*", "compact3" },
            { "javax.xml.crypto.dom.*", "compact3" },
            { "javax.xml.crypto.dsig.*", "compact3" },
            { "javax.xml.crypto.dsig.dom.*", "compact3" },
            { "javax.xml.crypto.dsig.keyinfo.*", "compact3" },
            { "javax.xml.crypto.dsig.spec.*", "compact3" },
            { "javax.xml.datatype.*", "compact2" },
            { "javax.xml.namespace.*", "compact2" },
            { "javax.xml.parsers.*", "compact2" },
            { "javax.xml.stream.*", "compact2" },
            { "javax.xml.stream.events.*", "compact2" },
            { "javax.xml.stream.util.*", "compact2" },
            { "javax.xml.transform.*", "compact2" },
            { "javax.xml.transform.dom.*", "compact2" },
            { "javax.xml.transform.sax.*", "compact2" },
            { "javax.xml.transform.stax.*", "compact2" },
            { "javax.xml.transform.stream.*", "compact2" },
            { "javax.xml.validation.*", "compact2" },
            { "javax.xml.xpath.*", "compact2" },
            { "jdk.*", "compact1" },
            { "standalone.jdk.internal.org.objectweb.asm.*", "hidden" },
            { "standalone.jdk.internal.org.objectweb.asm.commons.*", "hidden" },
            { "standalone.jdk.internal.org.objectweb.asm.signature.*", "hidden" },
            { "standalone.jdk.internal.org.objectweb.asm.tree.*", "hidden" },
            { "standalone.jdk.internal.org.objectweb.asm.tree.analysis.*", "hidden" },
            { "standalone.jdk.internal.org.objectweb.asm.util.*", "hidden" },
            { "standalone.jdk.internal.org.xml.sax.*", "hidden" },
            { "standalone.jdk.internal.org.xml.sax.helpers.*", "hidden" },
            { "standalone.jdk.internal.util.xml.*", "hidden" },
            { "standalone.jdk.internal.util.xml.impl.*", "hidden" },
            { "jdk.net.*", "compact1" },
            { "org.ietf.jgss.*", "compact3" },
            { "org.jcp.xml.dsig.internal.*", "hidden" },
            { "org.jcp.xml.dsig.internal.dom.*", "hidden" },
            { "org.w3c.dom.*", "compact2" },
            { "org.w3c.dom.bootstrap.*", "compact2" },
            { "org.w3c.dom.css.*", "compact2" },
            { "org.w3c.dom.events.*", "compact2" },
            { "org.w3c.dom.html.*", "compact2" },
            { "org.w3c.dom.ls.*", "compact2" },
            { "org.w3c.dom.ranges.*", "compact2" },
            { "org.w3c.dom.stylesheets.*", "compact2" },
            { "org.w3c.dom.traversal.*", "compact2" },
            { "org.w3c.dom.views.*", "compact2" },
            { "org.w3c.dom.xpath.*", "hidden" },
            { "org.xml.sax.*", "compact2" },
            { "org.xml.sax.ext.*", "compact2" },
            { "org.xml.sax.helpers.*", "compact2" },
            { "sun.applet.*", "proprietary" },
            { "sun.applet.resources.*", "proprietary" },
            { "sun.awt.*", "proprietary" },
            { "sun.awt.X11.*", "proprietary" },
            { "sun.awt.datatransfer.*", "proprietary" },
            { "sun.awt.dnd.*", "proprietary" },
            { "sun.awt.event.*", "hidden" },
            { "sun.awt.geom.*", "proprietary" },
            { "sun.awt.im.*", "proprietary" },
            { "sun.awt.image.*", "proprietary" },
            { "sun.awt.motif.*", "proprietary" },
            { "sun.awt.resources.*", "proprietary" },
            { "sun.awt.shell.*", "proprietary" },
            { "sun.awt.util.*", "hidden" },
            { "sun.awt.windows.*", "proprietary" },
            { "sun.corba.*", "proprietary" },
            { "sun.datatransfer.*", "hidden" },
            { "sun.font.*", "proprietary" },
            { "sun.instrument.*", "proprietary compact3" },
            { "sun.invoke.*", "hidden" },
            { "sun.invoke.anon.*", "hidden" },
            { "sun.invoke.empty.*", "hidden" },
            { "sun.invoke.util.*", "hidden" },
            { "sun.io.*", "proprietary compact1" },
            { "sun.java2d.*", "proprietary" },
            { "sun.java2d.cmm.*", "hidden" },
            { "sun.java2d.cmm.lcms.*", "hidden" },
            { "sun.java2d.d3d.*", "hidden" },
            { "sun.java2d.jules.*", "hidden" },
            { "sun.java2d.loops.*", "proprietary" },
            { "sun.java2d.opengl.*", "proprietary" },
            { "sun.java2d.pipe.*", "proprietary" },
            { "sun.java2d.pipe.hw.*", "hidden" },
            { "sun.java2d.pisces.*", "hidden" },
            { "sun.java2d.windows.*", "hidden" },
            { "sun.java2d.x11.*", "hidden" },
            { "sun.java2d.xr.*", "hidden" },
            { "sun.launcher.*", "hidden" },
            { "sun.launcher.resources.*", "hidden" },
            { "sun.lwawt.*", "hidden" },
            { "sun.lwawt.macosx.*", "hidden" },
            { "sun.management.*", "proprietary compact3" },
            { "sun.management.counter.*", "proprietary compact3" },
            { "sun.management.counter.perf.*", "proprietary compact3" },
            { "sun.management.jdp.*", "hidden" },
            { "sun.management.jmxremote.*", "proprietary compact3" },
            { "sun.management.resources.*", "proprietary compact3" },
            { "sun.misc.*", "proprietary compact1" },
            { "sun.misc.resources.*", "proprietary compact1" },
            { "sun.net.*", "proprietary compact1" },
            { "sun.net.dns.*", "proprietary compact3" },
            { "sun.net.ftp.*", "proprietary" },
            { "sun.net.ftp.impl.*", "hidden" },
            { "sun.net.httpserver.*", "hidden" },
            { "sun.net.idn.*", "hidden" },
            { "sun.net.sdp.*", "hidden" },
            { "sun.net.smtp.*", "proprietary" },
            { "sun.net.spi.*", "proprietary compact1" },
            { "sun.net.spi.nameservice.*", "proprietary compact1" },
            { "sun.net.util.*", "proprietary compact1" },
            { "sun.net.www.*", "proprietary compact1" },
            { "sun.net.www.content.audio.*", "proprietary" },
            { "sun.net.www.content.image.*", "proprietary" },
            { "sun.net.www.content.text.*", "proprietary" },
            { "sun.net.www.http.*", "proprietary compact1" },
            { "sun.net.www.protocol.file.*", "proprietary compact1" },
            { "sun.net.www.protocol.ftp.*", "proprietary" },
            { "sun.net.www.protocol.http.*", "proprietary compact1" },
            { "sun.net.www.protocol.http.logging.*", "hidden" },
            { "sun.net.www.protocol.http.ntlm.*", "hidden" },
            { "sun.net.www.protocol.http.spnego.*", "hidden" },
            { "sun.net.www.protocol.https.*", "proprietary compact1" },
            { "sun.net.www.protocol.jar.*", "proprietary compact1" },
            { "sun.net.www.protocol.mailto.*", "proprietary" },
            { "sun.net.www.protocol.netdoc.*", "proprietary" },
            { "sun.nio.*", "proprietary compact1" },
            { "sun.nio.ch.*", "proprietary compact1" },
            { "sun.nio.ch.sctp.*", "hidden" },
            { "sun.nio.cs.*", "proprietary compact1" },
            { "sun.nio.fs.*", "hidden" },
            { "sun.print.*", "proprietary" },
            { "sun.print.resources.*", "proprietary" },
            { "sun.reflect.*", "proprietary compact1" },
            { "sun.reflect.annotation.*", "proprietary compact1" },
            { "sun.reflect.generics.factory.*", "proprietary compact1" },
            { "sun.reflect.generics.parser.*", "proprietary compact1" },
            { "sun.reflect.generics.reflectiveObjects.*", "proprietary compact1" },
            { "sun.reflect.generics.repository.*", "proprietary compact1" },
            { "sun.reflect.generics.scope.*", "proprietary compact1" },
            { "sun.reflect.generics.tree.*", "proprietary compact1" },
            { "sun.reflect.generics.visitor.*", "proprietary compact1" },
            { "sun.reflect.misc.*", "hidden" },
            { "sun.rmi.log.*", "proprietary compact2" },
            { "sun.rmi.registry.*", "proprietary compact2" },
            { "sun.rmi.runtime.*", "proprietary compact2" },
            { "sun.rmi.server.*", "proprietary compact2" },
            { "sun.rmi.transport.*", "proprietary compact2" },
            { "sun.rmi.transport.proxy.*", "proprietary compact2" },
            { "sun.rmi.transport.tcp.*", "proprietary compact2" },
            { "sun.security.action.*", "proprietary compact1" },
            { "sun.security.jca.*", "proprietary compact1" },
            { "sun.security.jgss.*", "proprietary compact3" },
            { "sun.security.jgss.krb5.*", "proprietary compact3" },
            { "sun.security.jgss.spi.*", "proprietary compact3" },
            { "sun.security.jgss.spnego.*", "hidden" },
            { "sun.security.jgss.wrapper.*", "hidden" },
            { "sun.security.krb5.*", "proprietary compact3" },
            { "sun.security.krb5.internal.*", "proprietary compact3" },
            { "sun.security.krb5.internal.ccache.*", "proprietary compact3" },
            { "sun.security.krb5.internal.crypto.*", "proprietary compact3" },
            { "sun.security.krb5.internal.crypto.dk.*", "proprietary compact3" },
            { "sun.security.krb5.internal.ktab.*", "proprietary compact3" },
            { "sun.security.krb5.internal.rcache.*", "proprietary compact3" },
            { "sun.security.krb5.internal.tools.*", "proprietary compact3" },
            { "sun.security.krb5.internal.util.*", "proprietary compact3" },
            { "sun.security.pkcs.*", "proprietary compact1" },
            { "sun.security.pkcs10.*", "hidden" },
            { "sun.security.pkcs12.*", "hidden" },
            { "sun.security.provider.*", "proprietary compact1" },
            { "sun.security.provider.certpath.*", "proprietary compact1" },
            { "sun.security.provider.certpath.ldap.*", "hidden" },
            { "sun.security.provider.certpath.ssl.*", "hidden" },
            { "sun.security.rsa.*", "proprietary compact1" },
            { "sun.security.smartcardio.*", "hidden" },
            { "sun.security.timestamp.*", "proprietary compact1" },
            { "sun.security.tools.*", "proprietary compact1" },
            { "sun.security.tools.keytool.*", "hidden" },
            { "sun.security.tools.policytool.*", "hidden" },
            { "sun.security.util.*", "proprietary compact1" },
            { "sun.security.validator.*", "proprietary compact1" },
            { "sun.security.x509.*", "proprietary compact1" },
            { "sun.swing.*", "proprietary" },
            { "sun.swing.icon.*", "hidden" },
            { "sun.swing.plaf.*", "hidden" },
            { "sun.swing.plaf.synth.*", "proprietary" },
            { "sun.swing.plaf.windows.*", "hidden" },
            { "sun.swing.table.*", "hidden" },
            { "sun.swing.text.*", "hidden" },
            { "sun.swing.text.html.*", "hidden" },
            { "sun.text.*", "proprietary compact1" },
            { "sun.text.bidi.*", "hidden" },
            { "sun.text.normalizer.*", "hidden" },
            { "sun.text.resources.*", "proprietary compact1" },
            { "sun.text.resources.en.*", "hidden" },
            { "standalone.sun.tools.jar.*", "proprietary" },
            { "standalone.sun.tools.jar.resources.*", "proprietary" },
            { "sun.tracing.*", "hidden" },
            { "sun.tracing.dtrace.*", "hidden" },
            { "sun.util.*", "proprietary compact1" },
            { "sun.util.calendar.*", "proprietary compact1" },
            { "sun.util.cldr.*", "hidden" },
            { "sun.util.locale.*", "proprietary compact1" },
            { "sun.util.locale.provider.*", "hidden" },
            { "sun.util.logging.*", "hidden" },
            { "sun.util.logging.resources.*", "proprietary compact1" },
            { "sun.util.resources.*", "hidden" },
            { "sun.util.resources.en.*", "hidden" },
            { "sun.util.spi.*", "hidden" },
        };
    }
}
